const { defineSecret } = require('firebase-functions/params');
const { VertexAI } = require('@google-cloud/vertexai');
const admin = require('firebase-admin');
const llmCredentials = require('./llmCredentials');

const OPENROUTER_API_KEY_SECRET = defineSecret('OPENROUTER_API_KEY');

const VERTEX_PROJECT  = 'bob20250810';
const VERTEX_LOCATION = 'europe-west2';
const VERTEX_DEFAULT_MODEL = 'gemini-2.5-flash';

const OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1';
// 'auto' routes to whatever underlying model OpenRouter judges best for the
// request — paid, not subject to the free tier's 8 req/min cap that caused a
// production incident on 2026-07-16 (see git history: the nightly chain blew
// its function timeout retrying a dead/rate-limited free model on every
// candidate). This is now the primary path for every BOB LLM call, per
// explicit direction 2026-07-17: standardise BOB and Hermes on OpenRouter
// auto rather than mixing Vertex/free-tier/local models.
const OPENROUTER_MODEL = 'openrouter/auto';
const ALERT_EMAIL_TO = 'Jdonnelly@jc1.tech';

// ---------------------------------------------------------------------------
// Vertex AI (fallback)
// ---------------------------------------------------------------------------

async function _callVertexAI(systemPrompt, userPrompt, modelName) {
  const vertexAI = new VertexAI({ project: VERTEX_PROJECT, location: VERTEX_LOCATION });
  const model = vertexAI.getGenerativeModel({
    model: modelName || VERTEX_DEFAULT_MODEL,
    systemInstruction: systemPrompt ? { role: 'system', parts: [{ text: systemPrompt }] } : undefined,
    generationConfig: { temperature: 0.2, maxOutputTokens: 2048 },
  });
  const result = await model.generateContent(userPrompt);
  const text = result.response?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('Vertex AI returned an empty response');
  return text.replace(/```json\n?|\n?```/g, '').trim();
}

// ---------------------------------------------------------------------------
// OpenRouter (primary)
// ---------------------------------------------------------------------------

async function _callOpenRouterModel(apiKey, model, systemPrompt, userPrompt) {
  const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
      'HTTP-Referer': 'https://bob.jc1.tech',
      'X-Title': 'BOB',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.2,
      max_tokens: 2048,
    }),
  });
  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`OpenRouter Error: ${response.status} - ${errorText}`);
  }
  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) throw new Error('No content generated by OpenRouter');
  return text.replace(/```json\n?|\n?```/g, '').trim();
}

async function _callOpenRouter(apiKey, systemPrompt, userPrompt) {
  return _callOpenRouterModel(apiKey, OPENROUTER_MODEL, systemPrompt, userPrompt);
}

// ---------------------------------------------------------------------------
// User-key providers (bring-your-own-key)
//
// Vertex above runs on ADC and bills the BOB project. These are the equivalents that run on a
// key the user supplied, and they are what every non-exempt account uses. Deliberately plain
// text-in/text-out to match `callLLM`'s contract — no JSON mode, no tools.
// ---------------------------------------------------------------------------

const _stripFences = (text) => String(text || '').replace(/```json\n?|\n?```/g, '').trim();

async function _callUserGemini(apiKey, systemPrompt, userPrompt, modelName) {
  const { GoogleGenerativeAI } = require('@google/generative-ai');
  const model = new GoogleGenerativeAI(apiKey).getGenerativeModel({
    model: modelName || VERTEX_DEFAULT_MODEL,
    systemInstruction: systemPrompt || undefined,
    generationConfig: { temperature: 0.2, maxOutputTokens: 2048 },
  });
  const result = await model.generateContent(userPrompt);
  const text = typeof result?.response?.text === 'function' ? result.response.text() : null;
  if (!text) throw new Error('Gemini returned an empty response');
  return _stripFences(text);
}

async function _callUserAnthropic(apiKey, systemPrompt, userPrompt, modelName) {
  const resp = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({
      model: modelName || 'claude-haiku-4-5-20251001',
      max_tokens: 2048,
      system: systemPrompt || undefined,
      messages: [{ role: 'user', content: userPrompt }],
      temperature: 0.2,
    }),
  });
  if (!resp.ok) throw new Error(`Anthropic HTTP ${resp.status}: ${await resp.text()}`);
  const data = await resp.json();
  const text = data?.content?.[0]?.text;
  if (!text) throw new Error('Anthropic returned an empty response');
  return _stripFences(text);
}

async function _callUserOpenAI(apiKey, systemPrompt, userPrompt, modelName) {
  const resp = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: modelName || 'gpt-4o-mini',
      temperature: 0.2,
      max_tokens: 2048,
      messages: [
        { role: 'system', content: systemPrompt || '' },
        { role: 'user', content: userPrompt },
      ],
    }),
  });
  if (!resp.ok) throw new Error(`OpenAI HTTP ${resp.status}: ${await resp.text()}`);
  const data = await resp.json();
  const text = data?.choices?.[0]?.message?.content;
  if (!text) throw new Error('OpenAI returned an empty response');
  return _stripFences(text);
}

/**
 * Runs one call on the user's own credentials.
 *
 * A model name chosen for Vertex (e.g. 'gemini-2.5-flash') is meaningless to Anthropic or
 * OpenAI, so the caller's `modelName` is only honoured when the user is actually on Gemini;
 * otherwise their configured model, then the provider default, wins.
 */
async function _callWithUserKey({ provider, apiKey, model, systemPrompt, userPrompt, callerModel }) {
  switch (provider) {
    case 'anthropic':
      return _callUserAnthropic(apiKey, systemPrompt, userPrompt, model);
    case 'openai':
      return _callUserOpenAI(apiKey, systemPrompt, userPrompt, model);
    case 'openrouter':
      return _callOpenRouterModel(apiKey, model || OPENROUTER_MODEL, systemPrompt, userPrompt);
    default:
      return _callUserGemini(apiKey, systemPrompt, userPrompt, model || callerModel);
  }
}

// ---------------------------------------------------------------------------
// Failure alerting — one email per failed job, best-effort (never throws)
// ---------------------------------------------------------------------------

async function _sendModelFailureEmail(purpose, primaryError, fallbackError) {
  try {
    const { sendEmail } = require('../lib/email');
    await sendEmail({
      to: ALERT_EMAIL_TO,
      subject: `BOB: AI model failed${purpose ? ` (${purpose})` : ''}`,
      text: [
        `OpenRouter (${OPENROUTER_MODEL}) failed${purpose ? ` for job "${purpose}"` : ''}.`,
        `OpenRouter error: ${primaryError?.message || primaryError}`,
        fallbackError
          ? `Vertex AI fallback also failed: ${fallbackError?.message || fallbackError}`
          : 'Vertex AI fallback was not attempted or was unavailable.',
      ].join('\n\n'),
    });
  } catch (emailError) {
    console.error('[llmHelper] failed to send model-failure alert email:', emailError?.message || emailError);
  }
}

// ---------------------------------------------------------------------------
// Public interface — same signature as before: callLLM(system, user, model?)
//
// 2026-07-17: standardised on OpenRouter 'auto' as the primary path for every
// caller, per explicit direction. Vertex is the fallback on OpenRouter
// failure, using whichever Vertex-flavoured model name the caller originally
// passed (OpenRouter auto ignores that param — its whole point is picking
// the model itself). callLLMFreeFirst is kept as a thin alias so existing
// call sites (youtubeIngestion.js, aiPlanning.js) don't need touching —
// there's no separate free-tier path any more.
// ---------------------------------------------------------------------------

// 2026-08-01: Vertex is now the primary and OpenRouter the fallback — the reverse of the
// 2026-07-17 arrangement, per Jim.
//
// Two reasons. OpenRouter has been returning `402 Insufficient credits` since at least
// 2026-08-01, so every call paid the latency of a guaranteed failure before falling
// through; the nightly briefing has been running on the fallback path for days without
// anything saying so. And Jim is in China from September, where Vertex is reachable and
// OpenRouter may not be — a primary that cannot be reached is not a primary.
//
// This delegates to `callLLMVertexFirst` rather than restating the logic, so there is one
// ordering in this file and not two that can drift. That function already falls back to
// OpenRouter only on quota/503, which is the right trigger: a malformed prompt should fail
// loudly, not quietly get a second opinion from a different model.
// 2026-08-05: bring-your-own-key. The Vertex/OpenRouter pair below is BOB's own
// infrastructure and bills the project, so it is now reachable only by the accounts in
// llmCredentials.exemptUids(). Every other user runs on the key they configured in
// Settings → AI, and a user with no key gets a `missing_key` error they can act on rather
// than free usage on the owner's account.
//
// `userId` is therefore required in practice. It is an option rather than a positional
// argument so the existing `callLLM(system, user, model)` shape still reads the same at the
// ~10 call sites, but omitting it now means "no user" and fails closed.
async function callLLM(systemPrompt, userPrompt, modelName = VERTEX_DEFAULT_MODEL, { userId = null, purpose = null } = {}) {
  return callLLMVertexFirst(systemPrompt, userPrompt, modelName, { userId, purpose });
}

async function callLLMVertexFirst(systemPrompt, userPrompt, modelName = VERTEX_DEFAULT_MODEL, { userId = null, purpose = null } = {}) {
  if (!llmCredentials.isExempt(userId)) {
    return _callAsUser({ systemPrompt, userPrompt, modelName, userId, purpose });
  }

  try {
    return await _callVertexAI(systemPrompt, userPrompt, modelName);
  } catch (vertexError) {
    const msg = String(vertexError?.message || '').toLowerCase();
    const shouldFallback = msg.includes('429') || msg.includes('quota') || msg.includes('503') ||
      msg.includes('too many requests') || msg.includes('service unavailable');

    const openRouterKey = (process.env.OPENROUTER_API_KEY || '').trim();
    if (shouldFallback && openRouterKey) {
      console.warn('[llmHelper] Vertex AI quota/error — falling back to OpenRouter:', vertexError.message);
      return await _callOpenRouter(openRouterKey, systemPrompt, userPrompt);
    }

    // Non-quota errors or no fallback key: rethrow
    throw vertexError;
  }
}

/** The non-exempt path: resolve the user's own provider and key, then call it. */
async function _callAsUser({ systemPrompt, userPrompt, modelName, userId, purpose }) {
  if (!userId) {
    // A call with no user attached cannot be billed to anyone but the owner, which is exactly
    // what BYOK exists to prevent. Fail closed and name the caller so it can be fixed.
    throw new llmCredentials.LLMCredentialError(
      llmCredentials.CODES.MISSING_KEY,
      `An AI call was made with no user attached${purpose ? ` (${purpose})` : ''}, so there is no key to charge it to.`,
      { purpose },
    );
  }

  let profile = {};
  try {
    const snap = await admin.firestore().collection('profiles').doc(userId).get();
    profile = snap.exists ? (snap.data() || {}) : {};
  } catch (e) {
    console.warn('[llmHelper] profile lookup failed:', e?.message);
  }

  const featureKey = purpose ? llmCredentials.featureForPurpose(purpose) : null;
  let creds;
  try {
    creds = llmCredentials.resolveCredentials({ profile, userId, featureKey, purpose });
  } catch (err) {
    await llmCredentials.reportFailure(userId, err, { provider: err.provider, model: err.model, purpose });
    throw err;
  }

  try {
    const text = await _callWithUserKey({
      provider: creds.provider,
      apiKey: creds.apiKey,
      model: creds.model,
      systemPrompt,
      userPrompt,
      callerModel: modelName,
    });
    await llmCredentials.recordLLMStatus(userId, { ok: true, provider: creds.provider, model: creds.model });
    return text;
  } catch (err) {
    await llmCredentials.reportFailure(userId, err, { provider: creds.provider, model: creds.model, purpose });
    throw err;
  }
}

async function callLLMFreeFirst(systemPrompt, userPrompt, { modelName, purpose, userId = null } = {}) {
  return callLLM(systemPrompt, userPrompt, modelName, { userId, purpose });
}

module.exports = {
  callLLM,
  callLLMVertexFirst,
  callLLMFreeFirst,
  _callVertexAI,
  _callOpenRouter,
  _callOpenRouterModel,
  VERTEX_PROJECT,
  VERTEX_LOCATION,
  VERTEX_DEFAULT_MODEL,
  OPENROUTER_MODEL,
};
