const { defineSecret } = require('firebase-functions/params');
const { VertexAI } = require('@google-cloud/vertexai');

const OPENROUTER_API_KEY_SECRET = defineSecret('OPENROUTER_API_KEY');

const VERTEX_PROJECT  = 'bob20250810';
const VERTEX_LOCATION = 'europe-west2';
const VERTEX_DEFAULT_MODEL = 'gemini-2.5-flash';

const OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1';
// Use 'auto' so OpenRouter picks the best available model as fallback
const OPENROUTER_FALLBACK_MODEL = 'openrouter/auto';

// ---------------------------------------------------------------------------
// Vertex AI (primary)
// ---------------------------------------------------------------------------

async function _callVertexAI(systemPrompt, userPrompt, modelName) {
  const vertexAI = new VertexAI({ project: VERTEX_PROJECT, location: VERTEX_LOCATION });
  const model = vertexAI.getGenerativeModel({
    model: modelName || VERTEX_DEFAULT_MODEL,
    systemInstruction: systemPrompt ? { role: 'system', parts: [{ text: systemPrompt }] } : undefined,
    generationConfig: { temperature: 0.2, maxOutputTokens: 2048 },
  });
  const result = await model.generateContent(userPrompt);
  const text = result.response?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('Vertex AI returned an empty response');
  return text.replace(/```json\n?|\n?```/g, '').trim();
}

// ---------------------------------------------------------------------------
// OpenRouter (fallback)
// ---------------------------------------------------------------------------

async function _callOpenRouter(apiKey, systemPrompt, userPrompt) {
  const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
      'HTTP-Referer': 'https://bob.jc1.tech',
      'X-Title': 'BOB',
    },
    body: JSON.stringify({
      model: OPENROUTER_FALLBACK_MODEL,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.2,
      max_tokens: 2048,
    }),
  });
  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`OpenRouter Error: ${response.status} - ${errorText}`);
  }
  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) throw new Error('No content generated by OpenRouter');
  return text.replace(/```json\n?|\n?```/g, '').trim();
}

// ---------------------------------------------------------------------------
// Public interface — same signature as before: callLLM(system, user, model?)
// Primary: Vertex AI (ADC — no API key needed)
// Fallback: OpenRouter (when Vertex quota/error)
// ---------------------------------------------------------------------------

async function callLLM(systemPrompt, userPrompt, modelName = VERTEX_DEFAULT_MODEL) {
  try {
    return await _callVertexAI(systemPrompt, userPrompt, modelName);
  } catch (vertexError) {
    const msg = String(vertexError?.message || '').toLowerCase();
    const shouldFallback = msg.includes('429') || msg.includes('quota') || msg.includes('503') ||
      msg.includes('too many requests') || msg.includes('service unavailable');

    const openRouterKey = (process.env.OPENROUTER_API_KEY || '').trim();
    if (shouldFallback && openRouterKey) {
      console.warn('[llmHelper] Vertex AI quota/error — falling back to OpenRouter:', vertexError.message);
      return await _callOpenRouter(openRouterKey, systemPrompt, userPrompt);
    }

    // Non-quota errors or no fallback key: rethrow
    throw vertexError;
  }
}

module.exports = { callLLM, _callVertexAI, _callOpenRouter, VERTEX_PROJECT, VERTEX_LOCATION, VERTEX_DEFAULT_MODEL };
