const { defineSecret } = require('firebase-functions/params');

const GOOGLE_AI_STUDIO_API_KEY = defineSecret('GOOGLEAISTUDIOAPIKEY');
const OPENROUTER_API_KEY_SECRET = defineSecret('OPENROUTER_API_KEY');

const OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1';
const OPENROUTER_AUTO_MODEL = 'openrouter/auto';

async function _callGoogleAI(apiKey, systemPrompt, userPrompt, modelName) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
  const payload = {
    contents: [{ role: 'user', parts: [{ text: `${systemPrompt}\n\n${userPrompt}` }] }],
    generationConfig: { temperature: 0.2, maxOutputTokens: 2048 },
  };
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google AI Error: ${response.status} - ${errorText}`);
  }
  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('No content generated by Google AI');
  return text.replace(/```json\n?|\n?```/g, '').trim();
}

async function _callOpenRouter(apiKey, systemPrompt, userPrompt) {
  const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
      'HTTP-Referer': 'https://bob20250810.web.app',
      'X-Title': 'BOB',
    },
    body: JSON.stringify({
      model: OPENROUTER_AUTO_MODEL,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.2,
      max_tokens: 2048,
    }),
  });
  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`OpenRouter Error: ${response.status} - ${errorText}`);
  }
  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) throw new Error('No content generated by OpenRouter');
  return text.replace(/```json\n?|\n?```/g, '').trim();
}

/**
 * Calls the LLM with the given system and user prompts.
 * Tries Google AI Studio first; falls back to OpenRouter if unavailable or failing.
 */
async function callLLM(systemPrompt, userPrompt, modelName = (process.env.GEMINI_MODEL || 'gemini-2.5-flash-lite')) {
  const googleKey = (process.env.GOOGLEAISTUDIOAPIKEY || '').trim();
  const openRouterKey = (process.env.OPENROUTER_API_KEY || '').trim();

  if (!openRouterKey) {
    // Secret not injected — add OPENROUTER_API_KEY_SECRET to this function's secrets array
    console.warn('[llmHelper] OPENROUTER_API_KEY unavailable in this function runtime; fallback disabled');
  }

  if (googleKey) {
    try {
      return await _callGoogleAI(googleKey, systemPrompt, userPrompt, modelName);
    } catch (error) {
      console.warn('[llmHelper] Google AI failed, trying OpenRouter fallback:', error.message);
      if (openRouterKey) {
        return await _callOpenRouter(openRouterKey, systemPrompt, userPrompt);
      }
      throw error;
    }
  }

  if (openRouterKey) {
    return await _callOpenRouter(openRouterKey, systemPrompt, userPrompt);
  }

  throw new Error('No AI key available: neither GOOGLEAISTUDIOAPIKEY nor OPENROUTER_API_KEY is configured');
}

module.exports = { callLLM };
