name: CI (disabled)

on:
  workflow_dispatch:

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root deps
        run: npm ci || npm i
      - name: Install app deps (CRA)
        run: npm ci --prefix react-app || npm i --prefix react-app
      - name: Unit tests (CRA)
        run: npm test --prefix react-app -- --watchAll=false

  e2e:
    name: E2E Gate
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root deps
        run: npm ci || npm i
      - name: Install app deps (CRA)
        run: npm ci --prefix react-app || npm i --prefix react-app
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Build app
        run: npm run build --prefix react-app
      - name: Check version alignment
        run: node scripts/check-version-alignment.js
      - name: Run E2E (smoke)
        env:
          CI: true
          PW_USE_BUILD: '1'
          APP_BASE_URL: http://localhost:4173
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        run: npx playwright test
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Upload test results (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: test-results/junit.xml

  preview_and_notify:
    name: Preview & Notify (after E2E)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'pull_request'
    needs: [e2e]
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root deps
        run: npm ci || npm i
      - name: Install app deps
        run: npm ci --prefix react-app || npm i --prefix react-app
      - name: Build app
        run: npm run build --prefix react-app
      - name: Deploy to Firebase preview channel
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: pr-${{ github.event.pull_request.number }}
          expires: 7d
      - name: Telegram notify Ready for Validation
        if: ${{ steps.deploy.outputs.details_url != '' && secrets.TELEGRAM_BOT_TOKEN != '' && secrets.TELEGRAM_CHAT_ID != '' }}
        env:
          BOT: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT: ${{ secrets.TELEGRAM_CHAT_ID }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PREVIEW_URL: ${{ steps.deploy.outputs.details_url }}
        run: |
          TEXT=$(cat << 'EOF'
          ✅ E2E passed for PR #${PR_NUM}: ${PR_TITLE}
          Preview: ${PREVIEW_URL}
          PR: ${PR_URL}
          Production (unchanged): https://bob20250810.web.app
          Please validate preview and approve merge when ready.
          EOF
          )
          curl -s --data-urlencode "chat_id=${CHAT}" --data-urlencode "text=${TEXT}" "https://api.telegram.org/bot${BOT}/sendMessage"
      - name: Comment preview URL on PR
        if: ${{ steps.deploy.outputs.details_url != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const url = `${{ toJSON(steps.deploy.outputs.details_url) }}`.replace(/"/g,'');
            const body = `✅ E2E passed. Preview deployed: ${url}\n\nProduction (unchanged): https://bob20250810.web.app\n\nPlease validate and approve the merge when ready.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
