name: Firebase Hosting Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: firebase-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write
  pull-requests: write

env:
  PROJECT_ID: bob20250810

jobs:
  preview:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Install react-app deps
        run: npm ci --prefix react-app

      - name: Build react-app
        run: npm run build --prefix react-app

      - name: Deploy to Firebase Hosting (preview channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOB20250810 }}
          projectId: ${{ env.PROJECT_ID }}
          channelId: pr-${{ github.event.number }}
          expires: 7d

  production:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Install react-app deps
        run: npm ci --prefix react-app

      - name: Build react-app
        run: npm run build --prefix react-app

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOB20250810 }}

      - name: Deploy Firestore rules and indexes
        run: npx firebase-tools deploy --only firestore:rules,firestore:indexes --project $PROJECT_ID

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOB20250810 }}
          projectId: ${{ env.PROJECT_ID }}
          channelId: live

